'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{app,BrowserWindow,dialog,shell}=require('electron');
const root=process.env.XLD_GUITAR_TEST_ROOT,f=require(path.join(root,'fixture.json')),profile=path.join(root,'guitar-ui-profile-'+Date.now());fs.mkdirSync(profile);fs.copyFileSync(path.join(f.profile,'settings.json'),path.join(profile,'settings.json'));app.setPath('userData',profile);app.disableHardwareAcceleration();process.env.XLD_TEST='1';
const opened=[],errors=[],dialogs=[];let answer=0;dialog.showMessageBox=async(_w,options)=>{dialogs.push(options);return {response:answer};};shell.openPath=async p=>{assert(fs.existsSync(p));opened.push(p);return '';};
const trash=shell.trashItem.bind(shell);shell.trashItem=async dir=>{assert(path.resolve(dir).startsWith(path.resolve(f.directory)+path.sep+'midi'+path.sep+'guitar'+path.sep));await trash(dir);};
app.on('browser-window-created',(_e,w)=>w.webContents.on('console-message',e=>{if(e.level===3||e.level==='error')errors.push(e.message);}));require('../desktop/main.cjs');
app.whenReady().then(async()=>{let win;const wait=ms=>new Promise(r=>setTimeout(r,ms));try{
 for(let i=0;i<600;i++){win=BrowserWindow.getAllWindows()[0];if(win&&!win.webContents.isLoading())break;await wait(50);}
 const js=s=>win.webContents.executeJavaScript(s),until=async s=>{for(let i=0;i<600;i++){if(await js('Boolean('+s+')'))return;await wait(50);}throw Error('Timeout '+s);};await until('window.__xldAppReady');
 await js(`[...document.querySelectorAll('.album-card')].find(e=>e.textContent.includes(${JSON.stringify(f.track.album)})).click()`);await until(`document.querySelector('[data-track-id="${f.track.id}"]')`);await js(`document.querySelector('[data-track-id="${f.track.id}"]').click();document.querySelector('[data-workspace-tab=midi]').click()`);await until('document.querySelector("#derivedMidiSelect option[value=guitar]")');
 await js("document.querySelector('#derivedMidiSelect').value='guitar';document.querySelector('#derivedMidiSelect').dispatchEvent(new Event('change'))");await until('document.querySelector("[data-midi-engine=guitar-gaps][aria-pressed=true]")');assert.equal(await js('document.querySelector("#derivedModels").children.length'),3);assert((await js('document.querySelector("[data-midi-engine=guitar-gaps]").textContent')).includes('原声／清晰拨弦'));assert((await js('document.querySelector("[data-midi-engine=yourmt3-plus]").textContent')).includes('电吉他 · 试听'));
 const captures=[];async function capture(name,width,height,scale=1.2){win.setContentSize(width,height);await js(`document.documentElement.style.setProperty('--font-scale','${scale}')`);await wait(150);const v=await js(`(()=>{const c=document.querySelector('#workspaceContent'),r=c.getBoundingClientRect();return {fits:c.scrollHeight<=c.clientHeight+2,overflow:c.scrollWidth>c.clientWidth+1,clipped:[...c.querySelectorAll('button,select')].filter(e=>e.getClientRects().length).filter(e=>{const b=e.getBoundingClientRect();return b.left<r.left-1||b.right>r.right+1}).map(e=>e.id),deleteVisible:document.querySelector('#derivedDeleteMidi').getBoundingClientRect().bottom<=r.bottom};})()`);assert(!v.overflow);assert.deepEqual(v.clipped,[]);if(scale===1.2){assert(v.fits,name);assert(v.deleteVisible);}captures.push({name,...v});fs.writeFileSync(path.join(root,name+'.png'),(await win.webContents.capturePage()).toPNG());}
 await js('document.querySelector("[data-midi-engine=yourmt3-plus]").click()');assert((await js('document.querySelector("#midiBatchPlan").textContent')).includes('guitar · YourMT3+'));assert((await js('document.querySelector("#derivedTranscribe").textContent')).includes('使用'));
 await js('document.querySelector("#derivedTranscribe").click()');await until('!document.querySelector("#derivedTranscribe").disabled');assert((await js('document.querySelector("#midiMergeParts").textContent')).includes('guitar · YourMT3+'));await js('document.querySelector("#derivedMidi").click()');await wait(100);assert(opened.at(-1).includes(path.join('midi','guitar')));await js('document.querySelector("#midiBatchRun").click()');await until('!document.querySelector("#midiBatchRun").disabled && document.querySelector("#midiBatchStatus").textContent.includes("已就绪")');assert((await js('document.querySelector("#midiMergeParts").textContent')).includes('guitar · YourMT3+'));assert(!(await js('document.querySelector("#midiMergeFolder").disabled')));await capture('guitar-wide',1580,960);await capture('guitar-narrow',1180,780);
 // Cancel then actually recycle only this isolated copy; default GAPS is restored.
 await js('document.querySelector("#derivedDeleteMidi").click()');await until('!document.querySelector("#derivedDeleteMidi").disabled');assert.equal(dialogs.length,1);assert(dialogs[0].message.includes('YourMT3+'));answer=1;await js('document.querySelector("#derivedDeleteMidi").click()');await until('document.querySelector("#derivedStatus").textContent.includes("已启用 GAPS Guitar")');assert(await js('!!document.querySelector("[data-midi-engine=guitar-gaps][aria-pressed=true]")'));assert((await js('document.querySelector("#midiMergeParts").textContent')).includes('guitar · GAPS Guitar'));
 await js('document.querySelector("[data-midi-engine=yourmt3-plus]").click()');assert(await js('document.querySelector("#derivedDeleteMidi").disabled'));assert(!(await js('document.querySelector("#derivedMidi").disabled')));await js('document.querySelector("#derivedMidi").click()');await wait(80);assert.equal(path.basename(opened.at(-1)),'midi');await js('document.querySelector("#localeControl [data-locale=en-US]").click()');await until('document.querySelector("[data-midi-engine=yourmt3-plus]").textContent.includes("Electric guitar")');await capture('guitar-english',1580,960);await capture('guitar-large',1580,960,1.8);
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'guitar-ui.json'),JSON.stringify({passed:true,captures,opened,errors,checks:['three descriptive models','GAPS default','YourMT3 cache activation','one-click cached run and merge','merge selection','model folder','cancel deletion','isolated YourMT3 recycle','GAPS fallback','missing result controls','English','single-screen']},null,2));console.log('Guitar UI PASS');
}catch(e){console.error(e);if(win)fs.writeFileSync(path.join(root,'guitar-failure.png'),(await win.webContents.capturePage()).toPNG());process.exitCode=1;}finally{win?.destroy();app.exit(process.exitCode||0);}});
