'use strict';
const assert=require('node:assert/strict'),M=require('../midi-edit.js');
const original=[[1,2,60,80,2,31],[2.2,3.2,64,90,2,9]],snapshot=JSON.stringify(original);
const s=M.create(original,{duration:5,instrument:2});
assert(s.transform(['2:31','2:9'],{time:-10,pitch:100}));
let n=s.notes();assert.equal(n[0][0],0);assert.equal(n[1][0]-n[0][0],1.2000000000000002);assert.equal(n[1][2]-n[0][2],4);assert.equal(n[1][2],127);
assert(s.undo());assert.deepEqual(s.notes(),original);assert(!s.dirty());assert(s.redo());assert(s.undo());
s.set('2:31',[1,2.125,60,30]);assert.equal(s.notes()[0][3],30);
s.transform(['2:31'],{end:.125});assert.equal(s.notes()[0][1],2.25);
s.undo();assert.equal(s.notes()[0][1],2.125);assert(s.canRedo());
const id=s.add(4.8,70);assert(!s.canRedo());assert.equal(s.notes().find(n=>M.key(n)===id)[1],5);
s.remove([id]);s.undo();assert(s.notes().some(n=>M.key(n)===id));
assert.throws(()=>s.set('2:31',[2,1,60,20]),/invalid/);
const held=s.notes();assert.throws(()=>s.remove(s.notes().map(M.key)),/empty/);assert.deepEqual(s.notes(),held);
s.reset();assert(!s.dirty());s.undo();assert(s.dirty());
const recovered=M.create(original,{duration:5,instrument:2,restored:s.notes()});
assert(recovered.dirty());assert(!recovered.canUndo());assert(!recovered.canRedo());
assert.throws(()=>M.create(original,{duration:5,instrument:3}),/invalid/);
assert.equal(JSON.stringify(original),snapshot,'original tuples never mutated');
console.log('midi edit: ok (group deltas, clamping, duration, velocity, stable identities, one operation undo, recovered draft, original untouched)');
