const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {createStorage,guarded}=require('../core/storage.cjs');
(async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'xld-storage-')),album=path.join(root,'Artist - Album'),track=path.join(album,'01 Song__abcdef'),stems=crypto.randomUUID(),ref=crypto.randomUUID(),free=crypto.randomUUID();
 const write=async(file,value)=>{await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,typeof value==='object'&&!Buffer.isBuffer(value)?JSON.stringify(value):value);};
 const wav=(kind,id)=>write(path.join(track,kind,id,kind==='stems'?'guitar.wav':'target.wav'),Buffer.alloc(1024));
 await wav('stems',stems);await wav('refinement',ref);await wav('refinement',free);
 await write(path.join(track,'stems.json'),{kind:'stems',runId:stems,engine:'bs-roformer-sw'});
 await write(path.join(track,'refinement','a.json'),{kind:'refinement',runId:ref,parentRunId:stems,target:'strings',engine:'mega-53'});
 await write(path.join(track,'refinement','b.json'),{kind:'refinement',runId:free,parentRunId:null,target:'synth',sourceStem:'mix',engine:'mega-53'});
 await write(path.join(track,'refinement','kept','a.json'),{runId:ref});
 await write(path.join(track,'manual-tags.json'),{tag:'must survive'});
 let busy=false,confirmations=0,trashes=0;const manager=createStorage({getRoot:()=>root,isBusy:()=>busy,trash:async directory=>{trashes++;await fs.rename(directory,directory+'.recycled');}});
 const snapshot=()=>manager.scan(),find=async id=>(await snapshot()).rows.find(r=>r.runId===id),yes=async()=>{confirmations++;return true;};
 const initial=await snapshot();assert.equal(initial.rows.length,3);assert.equal(initial.wavBytes,3072);assert((await find(ref)).kept);assert((await find(stems)).blocked);
 await assert.rejects(manager.clear([await find(ref)],'permanent',yes),/取消保留/);assert.equal(confirmations,0);
 await assert.rejects(manager.clear([await find(stems)],'permanent',yes),/仍被/);
 busy=true;await assert.rejects(manager.protect(await find(free),true),/等待/);busy=false;
 const older=await find(free);await write(path.join(older.directory,'residual.wav'),Buffer.alloc(30));await assert.rejects(manager.clear([older],'permanent',yes),/已变化/);
 await manager.protect(await find(free),true);assert((await find(free)).kept);await manager.protect(await find(free),false);assert(!(await find(free)).kept);
 assert((await manager.clear([await find(free)],'permanent',async()=>false)).canceled);assert(await find(free));
 await assert.rejects(manager.clear([await find(free)],'permanent',async()=>{await write(path.join(track,'refinement',free,'user-notes.txt'),'personal');return true;}),/已变化|未知文件/);
 await fs.rm(path.join(track,'refinement',free,'user-notes.txt'));
 const trashed=await manager.clear([await find(free)],'trash',yes);assert.equal(trashed.deleted,1);assert.equal(trashes,1);assert(!await find(free));
 // Restore the directory: metadata was deliberately left intact.
 await fs.rename(path.join(track,'refinement',free)+'.recycled',path.join(track,'refinement',free));assert.equal((await find(free)).target,'synth');
 await manager.protect(await find(ref),false);assert(!(await find(ref)).kept);assert.equal(await fs.stat(path.join(track,'refinement','kept','a.json')).catch(()=>null),null);
 assert.equal((await manager.clear([await find(ref)],'permanent',yes)).deleted,1);assert(!(await find(stems)).blocked,'removed refinement no longer blocks its parent');
 const midiId=crypto.randomUUID();await write(path.join(track,'midi','guitar',midiId,'guitar.mid'),'MThd');await write(path.join(track,'midi','guitar','gaps.json'),{kind:'midi',runId:midiId,sourceRunId:stems,file:'midi/guitar/'+midiId+'/guitar.mid'});
 assert((await find(stems)).blocked,'MIDI dependency protects source');
 const midiId2=crypto.randomUUID();await write(path.join(track,'midi','guitar',midiId2,'guitar.mid'),'MThd');await write(path.join(track,'midi','guitar','runs',midiId2+'.json'),{kind:'midi',runId:midiId2,sourceRunId:stems,file:'midi/guitar/'+midiId2+'/guitar.mid'});
 const dangling=crypto.randomUUID();await write(path.join(track,'midi','guitar','runs',dangling+'.json'),{kind:'midi',runId:dangling,sourceRunId:stems,file:'midi/guitar/'+dangling+'/guitar.mid'});
 assert.equal((await find(stems)).dependencyCount,2,'per-run records protect the source; a record whose files are gone does not count');
 await assert.rejects(manager.clear([{id:'../../outside',revision:''}],'permanent',yes),/已变化/);
 await assert.rejects(guarded(root,path.dirname(root)),/path-invalid/);
 const outside=await fs.mkdtemp(path.join(os.tmpdir(),'xld-storage-outside-'));await write(path.join(outside,'private.txt'),'untouched');
 await fs.symlink(outside,path.join(track,'refinement',crypto.randomUUID()),'junction');const linked=await snapshot();assert(linked.warnings.length);assert.equal(await fs.readFile(path.join(outside,'private.txt'),'utf8'),'untouched');
 assert.equal(JSON.parse(await fs.readFile(path.join(track,'manual-tags.json'),'utf8')).tag,'must survive');
 console.log('Storage PASS: accounting, keep/unkeep, dependency protection, busy lock, changed-file rejection, confirmation, trash/restore, permanent deletion, traversal and junction safety; only disposable fixtures changed');
})().catch(error=>{console.error(error);process.exitCode=1;});
