'use strict';
const api=window.Setup,$=id=>document.getElementById(id);let english=new URLSearchParams(location.search).get('lang')==='en',state,selected='midi',busy=false,canSave=false;
const tr=(zh,en)=>english?en:zh;
function localize(){document.documentElement.lang=english?'en':'zh-CN';document.querySelectorAll('[data-zh]').forEach(el=>el.textContent=el.dataset[english?'en':'zh']);$('language').textContent=english?'中文':'English';}
function values(){return Object.fromEntries([...document.querySelectorAll('[data-key]')].map(el=>[el.dataset.key,el.value]));}
function lock(value){busy=value;document.querySelectorAll('button,input').forEach(el=>el.disabled=value);$('cancel').disabled=!value;$('save').disabled=value||!canSave;if(state?.isXml){$('library').disabled=true;$('output').disabled=true;}}
function render(){const g=state.groups.find(g=>g.id===selected);$('groups').replaceChildren();for(const group of state.groups){const b=document.createElement('button');b.textContent=group.label[+english];b.className=group.id===selected?'active':'';b.onclick=()=>{selected=group.id;render();};$('groups').append(b);}
 $('title').textContent=g.label[+english];$('notice').textContent=g.notice?.[+english]||'';$('fields').replaceChildren();
 for(const key of g.keys){const row=document.createElement('div');row.className='field';const label=document.createElement('label'),input=document.createElement('input'),line=document.createElement('div'),button=document.createElement('button');input.id='field-'+key;label.htmlFor=input.id;label.textContent=key.endsWith('_PYTHON')?tr('Python 解释器','Python interpreter'):tr('模型 / 后端目录','Model / backend directory');input.dataset.key=key;input.value=state.paths[key]||'';input.title=key;input.oninput=()=>{canSave=false;$('save').disabled=true;};button.textContent=tr('选择…','Browse…');button.onclick=async()=>{const r=await api.pick(selected,key);if(r.path){input.value=r.path;input.dispatchEvent(new Event('input'));}else if(r.error)$('status').textContent=r.error;};line.append(input,button);row.append(label,line);$('fields').append(row);}
 $('links').replaceChildren();g.links.forEach((url,index)=>{const b=document.createElement('button');b.textContent=tr('官方来源 / 条款','Official source / terms')+(g.links.length>1?' '+(index+1):'');b.title=url;b.onclick=()=>api.official(selected,index);$('links').append(b);});
 $('installCard').hidden=selected!=='midi';$('engines').replaceChildren();$('status').textContent='';canSave=false;lock(false);
}
function report(r){$('engines').replaceChildren();for(const e of r.engines||[]){const li=document.createElement('li');li.textContent=e.id+' · '+(e.available?tr('检查通过','Check passed'):tr('未就绪','Not ready'));$('engines').append(li);}$('status').textContent=r.ok?(r.scope==='midi-roundtrip'?tr('MIDI 读写验证通过，可以保存。','MIDI roundtrip passed. Ready to save.'):tr('至少一个模型检查通过，可以保存；其余未安装项不受影响。','At least one model passed. Ready to save independently.')):r.error||tr('缺少依赖或模型文件，请参考安装说明。','Dependencies or model files are missing. See the setup guide.');canSave=!!r.ok;}
async function perform(fn){lock(true);try{await fn();}catch(e){$('status').textContent=e.message;canSave=false;}finally{lock(false);}}
$('probe').onclick=()=>perform(async()=>{canSave=false;$('status').textContent=tr('正在检查，请稍候…','Checking…');report(await api.probe(selected,values()));});
$('save').onclick=()=>perform(async()=>{const current=values(),r=await api.save(selected,current);if(r.ok){Object.assign(state.paths,current);$('status').textContent=tr('已保存。请先保存工作，再关闭并重新打开 XLD / XML。','Saved. Save your work, then close and reopen XLD / XML.');}else $('status').textContent=r.error;});
$('install').onclick=()=>perform(async()=>{canSave=false;$('log').textContent='';const r=await api.install();if(r.ok){Object.assign(state.paths,r.values);for(const [k,v]of Object.entries(r.values))document.querySelector('[data-key="'+k+'"]').value=v;report(r.report);}else $('status').textContent=r.cancelled?tr('已取消，原配置未改动。','Cancelled; previous setup unchanged.'):r.error;});
$('cancel').onclick=()=>api.cancel();$('language').onclick=()=>{english=!english;localize();render();};
$('export').onclick=async()=>{const r=await api.export();if(!r.cancelled)$('status').textContent=r.ok?tr('诊断已导出，不包含歌曲、令牌或完整本机路径。','Diagnostics exported without songs, tokens or full local paths.'):r.error;};
for(const [id,method]of [['library','library'],['output','output']])$(id).onclick=async()=>{lock(true);try{const r=await api[method]();$('locationStatus').textContent=r.error?r.error:r.canceled?tr('已取消选择。','Selection cancelled.'):tr('位置已保存；回主窗口刷新曲库。','Location saved. Refresh the library in the main window.');}catch(e){$('locationStatus').textContent=e.message;}finally{lock(false);}};
api.log(text=>{$('log').textContent=($('log').textContent+text).slice(-18000);$('log').parentElement.open=true;});
(async()=>{localize();state=await api.state();if(!state.ok)throw Error(state.error);render();})().catch(e=>{$('status').textContent=e.message;});
